export const CHARACTER_ERROR = 'CHARACTER_ERROR';
export const CHARACTER_LOADING = 'CHARACTER_LOADING';
export const CHARACTER_FETCH_SUCCESSFUL = 'CHARACTER_FETCH_SUCCESSFUL';
export const CHARACTERS_FETCH_SUCCESSFUL = 'CHARACTERS_FETCH_SUCCESSFUL';
export const GET_ADD_TO_CHARACTERS_FETCH_SUCCESSFUL = 'GET_ADD_TO_CHARACTERS_FETCH_SUCCESSFUL';

export const MOVIE_ERROR = 'MOVIE_ERROR';
export const MOVIE_LOADING = 'MOVIE_LOADING';
export const MOVIE_FETCH_SUCCESSFUL = 'MOVIE_FETCH_SUCCESSFUL';
export const MOVIES_FETCH_SUCCESSFUL = 'MOVIES_FETCH_SUCCESSFUL';
